name: CI/CD Pull Request Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:

jobs:
  lint:
    uses: kurocado-studio/platform/.github/workflows/workflow.lint.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: lint
    uses: kurocado-studio/platform/.github/workflows/workflow.test.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
